name = "mnmfitness02"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "MNM_USERS"
id = "32a9fa2f787e4c659429f1ec9b710b27"

[[kv_namespaces]]
binding = "MNM_SESSIONS"
id = "7e617fadbdc148aeab897b7a81440a8f"
